version: "3"

services:
  pgcat:
    hostname: pgcat
    image: ghcr.io/postgresml/pgcat:latest
    volumes:
      - ./pgcat.toml:/etc/pgcat/pgcat.toml
    ports:
      - "6432:6432"
      - "9930:9930"
    networks:
      - yugabyte-network

networks:
  yugabyte-network:
    external: true
